/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32f103x8.h"
#include "stm32f103c6_GPIO_driver.h"

void GPIO_Init()
{

	GPIO_PINConfig_t pinCfig;

	//PA1 High-Z (floating) input
	pinCfig.GPIO_PinNumber = GPIO_PIN_1;
	pinCfig.GPIO_Mode = GPIO_MODE_INPUT_FLO;
	MCAL_GPIO_Init(GPIOA, &pinCfig);

	//PB1 output push pull mode
	//MODE 01: Output mode, max speed 10 MHz
	pinCfig.GPIO_PinNumber = GPIO_PIN_1;
	pinCfig.GPIO_Mode = GPIO_MODE_OUTPUT_PP;
	pinCfig.GPIO_Output_Speed = GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOB, &pinCfig);

	//PA13 High-Z (floating) input
	pinCfig.GPIO_PinNumber = GPIO_PIN_13;
	pinCfig.GPIO_Mode = GPIO_MODE_INPUT_FLO;
	MCAL_GPIO_Init(GPIOA, &pinCfig);

	//PB13 output push pull mode
	//MODE 01: Output mode, max speed 10 MHz
	pinCfig.GPIO_PinNumber = GPIO_PIN_13;
	pinCfig.GPIO_Mode = GPIO_MODE_OUTPUT_PP;
	pinCfig.GPIO_Output_Speed = GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOB, &pinCfig);
}

void Clock_Init(){

	//Enable clock of GPIOA
	RCC_GPIOA_CLK_EN();

	//Enable clock of GPIOB
	RCC_GPIOB_CLK_EN();

}

void my_wait(uint32_t time)
{
	uint32_t i, j;
	for(i = 0; i< time; i++)
		for(j =0; j < 255; j++);
}

int main(void)
{
	Clock_Init();
	GPIO_Init();

	while(1)
	{
		//PA1 >>>>>>> connected external pull up resistor
		if(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1) == 0) // press
		{
			MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_1); // single press
			while(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1) == 0);
		}

		//PA13 >>>>>>> connected external pull down resistor
		if(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_13) == 1) // multi pressing
			MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_13);


		my_wait(1);
	}

}
