/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdint.h>
typedef volatile uint32_t 	vuint32_t;

//RCC
#define RCC_BASE		0x40021000
#define RCC_APB2ENR		*(volatile uint32_t *) (RCC_BASE + 0x18)

//GPIOA
#define PORTA_BASE		0x40010800
#define GPIOA_CRL		*(volatile uint32_t *) (PORTA_BASE + 0x00)
#define GPIOA_CRH		*(volatile uint32_t *) (PORTA_BASE + 0x04)
#define GPIOA_ODR		*(volatile uint32_t *) (PORTA_BASE + 0x0c)
#define GPIOA_IDR		*(volatile uint32_t *) (PORTA_BASE + 0x08)

//GPIOB
#define PORTB_BASE		0x40010C00
#define GPIOB_CRL		*(volatile uint32_t *) (PORTB_BASE + 0x00)
#define GPIOB_CRH		*(volatile uint32_t *) (PORTB_BASE + 0x04)
#define GPIOB_ODR		*(volatile uint32_t *) (PORTB_BASE + 0x0c)
#define GPIOB_IDR		*(volatile uint32_t *) (PORTB_BASE + 0x08)


void GPIO_Init()
{
	GPIOA_CRL = 0x0;
	GPIOB_CRL = 0x0;

	//PA1 High-Z (floating) input
	GPIOA_CRL |= (1 << 6);

	//PB1 output push pull mode
	//CNF 00: General purpose output push-pull
	GPIOB_CRL &= ~(0b11 << 6);
	//MODE 01: Output mode, max speed 10 MHz
	GPIOB_CRL |= (0b01 << 4);

	//PA13 High-Z (floating) input
	GPIOA_CRH &= ~(0b11 << 20);
	GPIOA_CRH |= (0b01 << 22);

	//PB13 output push pull mode
	//CNF 00: General purpose output push-pull
	GPIOB_CRH &= ~(0b11 << 22);
	//MODE 01: Output mode, max speed 10 MHz
	GPIOB_CRH |= (0b01 << 20);

}

void Clock_Init(){

	//Enable clock of GPIOA
	RCC_APB2ENR |= 1 << 2;

	//Enable clock of GPIOB
	RCC_APB2ENR |= 1 << 3;

}

void my_wait(int n)
{
	unsigned int i, j;
	for(i = 0; i< n; i++)
		for(j =0; j < 255; j++);
}

int main(void)
{
	Clock_Init();
	GPIO_Init();



	while(1)
	{
		//PA1 >>>>>>> connected external pull up resistor
		if(((GPIOA_IDR & (1 << 1)) >> 1) == 0) // press
		{
			GPIOB_ODR ^= (1 << 1); // single press
			while(((GPIOA_IDR & (1 << 1)) >> 1) == 0);
		}

		//PA13 >>>>>>> connected external pull down resistor
		if(((GPIOA_IDR & (1 << 13)) >> 13) == 1) // multi pressing
			GPIOB_ODR ^= (1 << 13);


my_wait(1);
	}

}
