/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32f103x8.h"
#include "stm32f103c6_GPIO_driver.h"
#include "LCD.h"
#include "Keypad.h"
#include "SevenSegment.h"


void GPIO_Init()
{

	GPIO_PINConfig_t pinCfig;

	//PB9 output
	pinCfig.GPIO_PinNumber = Seven_SEGMENT_PIN0;
	pinCfig.GPIO_Mode = GPIO_MODE_OUTPUT_PP;
	pinCfig.GPIO_Output_Speed = GPIO_SPEED_10M;
	MCAL_GPIO_Init(Seven_Segment_Port, &pinCfig);

	//PB10 output
	pinCfig.GPIO_PinNumber = Seven_SEGMENT_PIN1;
	pinCfig.GPIO_Mode = GPIO_MODE_OUTPUT_PP;
	pinCfig.GPIO_Output_Speed = GPIO_SPEED_10M;
	MCAL_GPIO_Init(Seven_Segment_Port, &pinCfig);

	//PB11 output
	pinCfig.GPIO_PinNumber = Seven_SEGMENT_PIN2;
	pinCfig.GPIO_Mode = GPIO_MODE_OUTPUT_PP;
	pinCfig.GPIO_Output_Speed = GPIO_SPEED_10M;
	MCAL_GPIO_Init(Seven_Segment_Port, &pinCfig);

	//PB12 output
	pinCfig.GPIO_PinNumber = Seven_SEGMENT_PIN3;
	pinCfig.GPIO_Mode = GPIO_MODE_OUTPUT_PP;
	pinCfig.GPIO_Output_Speed = GPIO_SPEED_10M;
	MCAL_GPIO_Init(Seven_Segment_Port, &pinCfig);

	//PB13 output
	pinCfig.GPIO_PinNumber = Seven_SEGMENT_PIN4;
	pinCfig.GPIO_Mode = GPIO_MODE_OUTPUT_PP;
	pinCfig.GPIO_Output_Speed = GPIO_SPEED_10M;
	MCAL_GPIO_Init(Seven_Segment_Port, &pinCfig);

	//PB14 output
	pinCfig.GPIO_PinNumber = Seven_SEGMENT_PIN5;
	pinCfig.GPIO_Mode = GPIO_MODE_OUTPUT_PP;
	pinCfig.GPIO_Output_Speed = GPIO_SPEED_10M;
	MCAL_GPIO_Init(Seven_Segment_Port, &pinCfig);

	//PB15 output
	pinCfig.GPIO_PinNumber = Seven_SEGMENT_PIN6;
	pinCfig.GPIO_Mode = GPIO_MODE_OUTPUT_PP;
	pinCfig.GPIO_Output_Speed = GPIO_SPEED_10M;
	MCAL_GPIO_Init(Seven_Segment_Port, &pinCfig);

}

void Clock_Init(){

	//Enable clock of GPIOA
	RCC_GPIOA_CLK_EN();

	//Enable clock of GPIOB
	RCC_GPIOB_CLK_EN();

}

void my_wait(uint32_t time)
{
	uint32_t i, j;
	for(i = 0; i< time; i++)
		for(j =0; j < 255; j++);
}

int main(void)
{
	Clock_Init();
	GPIO_Init();
	IntLCD();
	uint8_t key_pressed;
	LCD_displayString("Hello Mohamed");
	my_wait(500);
	LCD_clearScreen();

	unsigned char seg[] = {ZERO, ONE, TWO, There, Four, FIVE, SIX, SEVEN, EIGHT, NINE, ZERO};
	unsigned char lcd[] = {'0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0'};

	for(unsigned char i = 0; i< 11; i++)
	{
		MCAL_GPIO_WritePort(Seven_Segment_Port, seg[i] << 9);
		LCD_displayCharacter(lcd[i]);
		my_wait(200);
	}
	LCD_clearScreen();
	Keypad_Init();
	LCD_displayString("keypad is ready");
	my_wait(500);
	LCD_clearScreen();

	while(1)
	{
		key_pressed = KeypadPressed();
		switch(key_pressed)
		{
		case 'A':
			break;

		case '?':
			LCD_clearScreen();
			break;

		default:
			LCD_displayCharacter(key_pressed);
			break;
		}

		my_wait(50);

		//		//PA1 >>>>>>> connected external pull up resistor
		//		if(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1) == 0) // press
		//		{
		//			MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_1); // single press
		//			while(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1) == 0);
		//		}
		//
		//		//PA13 >>>>>>> connected external pull down resistor
		//		if(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_13) == 1) // multi pressing
		//			MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_13);
		//
		//
		//		my_wait(1);
	}

}
