/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdint.h>
typedef volatile uint32_t 	vuint32_t;

//RCC
#define RCC_BASE		0x40021000
#define RCC_APB2ENR		*(volatile uint32_t *) (RCC_BASE + 0x18)

//GPIOA
#define PORTA_BASE		0x40010800
#define GPIOA_CRH		*(volatile uint32_t *) (PORTA_BASE + 0x04)
#define GPIOA_ODR		*(volatile uint32_t *) (PORTA_BASE + 0x0c)
#define GPIOA_CRL		*(volatile uint32_t *) (PORTA_BASE + 0x00)

//EXTI
#define EXTI_BASE		0x40010400
#define EXTI_IMR		*(volatile uint32_t *) (EXTI_BASE + 0x00)
#define EXTI_RTSR		*(volatile uint32_t *) (EXTI_BASE + 0x08)
#define EXTI_PR			*(volatile uint32_t *) (EXTI_BASE + 0x14)

//AFIO
#define AFIO_BASE		0x40010000
#define AFIO_EXTICR1	*(volatile uint32_t *) (AFIO_BASE + 0x08)

//NVIC
#define NVIC_BASE		0xE000E100
#define NVIC_ISER0		*(volatile uint32_t *) (NVIC_BASE + 0x00)


void GPIO_Init()
{
	//make pin 13 in port A is output
	GPIOA_CRH &= 0xff0fffff;
	GPIOA_CRH |= 0x00200000;

	//pinA0: Floating input (reset state)
	GPIOA_CRL |= (1 << 2);
}

void Clock_Init(){

	//Enable clock of GPIO
	RCC_APB2ENR |= 1 << 2;

	//Enable Alternate Function IO clock
	RCC_APB2ENR |= 1 << 0;

}

int main(void)
{
	GPIO_Init();
	Clock_Init();

	// EXTI 0 configuration pin 0
	AFIO_EXTICR1 = 0;

	//Enable Interrupt Mask on line 0
	EXTI_IMR |= (1 << 0);

	//Rising trigger enabled for Interrupt for input line 0
	EXTI_RTSR |= (1 << 0);

	//Enable NVIC IRQ6
	NVIC_ISER0 |= (1 << 6);

	while(1);

}

void EXTI0_IRQHandler (void)
{
	// IRQ is happened EXTI0 >>> POART pin 0 | rising edge

	//Toggle led pin 13
	GPIOA_ODR ^= (1 << 13);

	//clear pending request for line 0
	EXTI_PR |= (1 << 0);

}
